(deftheme acazzola-light
  "Created 2018-10-17.")

(custom-theme-set-faces
 'acazzola-light
 '(highlight ((t (:background "#acc3e6"))))
 '(region ((t (:background "#bcd5fa"))))
 '(mode-line ((t (:background "#bcd5fa" :foreground "black"))))
 '(minibuffer-prompt ((t (:foreground "#445588"))))
 '(link ((t (:foreground "blue1" :underline t))))
 '(fringe ((t (:background "gray95" :foreground "black"))))
 '(cursor ((t (:foreground "black" :background "black"))))
 '(show-paren-match ((t (:background "#bcd5fa" :foreground "white"))))
 '(show-paren-mismatch ((t (:bold t :background "#9d1e15" :foreground "#f8f8f8"))))
 '(font-lock-warning-face ((t (:background "#ffe4b5"))))
 '(font-lock-comment-face ((t (:italic t :foreground "#999999" :slant italic))))
 '(font-lock-comment-delimiter-face ((t (:inherit font-lock-comment-face))))
 '(font-lock-builtin-face ((t (:inherit default))))
 '(font-lock-constant-face ((t (:foreground "#3b5bb5"))))
 '(font-lock-doc-face ((t (:foreground "#409b1c"))))
 '(font-lock-function-name-face ((t (:inherit default :bold t))))
 '(font-lock-keyword-face ((t (:bold t :weight bold :foreground "#ff7800"))))
 '(font-lock-preprocessor-face ((t (:foreground "#3a4a64" :background "gray95"))))
 '(font-lock-regexp-grouping-backslash ((t (:inheirt font-lock-comment-face))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "red"))))
 '(font-lock-string-face ((t (:foreground "#409b1c"))))
 '(font-lock-type-face ((t (:foreground "#445588"))))
 '(font-lock-variable-name-face ((t (:foreground "#671ebb"))))
 '(compilation-info ((t (:inherit font-lock-string-face))))
 '(compilation-line-number ((t (:foreground "#3b5bb5"))))
 '(flycheck-error ((t (:inherit font-lock-warning-face))))
 '(flycheck-error-list-error ((t (:inherit font-lock-warning-face))))
 '(flycheck-fringe-error ((t (:inherit font-lock-warning-face))))
 '(diff-header ((t (:background "LightSteelBlue3"))))
 '(diff-file-header ((t (:inherit diff-header :bold t))))
 '(diff-added ((t (:background "DarkOliveGreen3"))))
 '(diff-removed ((t (:background "IndianRed1"))))
 '(diff-changed ((t (:background "burlywood3"))))
 '(diff-context ((t (:background "gray90"))))
 '(diff-index ((t (:inherit font-lock-comment-face))))
 '(org-done ((t (:inherit font-lock-string-face :bold t))))
 '(org-todo ((t (:inherit font-lock-variable-name-face :bold t))))
 '(org-level-1 ((t (:inherit default :underline t :bold t))))
 '(org-level-2 ((t (:inherit font-lock-variable-name-face))))
 '(org-level-3 ((t (:inherit font-lock-keyword-face))))
 '(org-level-4 ((t (:inherit font-lock-type-face))))
 '(org-special-keyword ((t (:inherit font-lock-doc-face))))
 '(default ((t (:bold nil :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "black" :background "#e6e6fa" :stipple nil :inherit nil)))))

(provide-theme 'acazzola-light)
